"""removed id

Revision ID: 01a32b598467
Revises: fa4862f4dab6
Create Date: 2025-09-15 12:53:24.951328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01a32b598467'
down_revision: Union[str, Sequence[str], None] = 'fa4862f4dab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contents', 'description',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('contents', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('contents', 'description',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###
