"""added new tables

Revision ID: a9d42be3c485
Revises: 9af94a66123a
Create Date: 2025-09-12 09:07:03.199336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9d42be3c485'
down_revision: Union[str, Sequence[str], None] = '9af94a66123a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('helpline_name', sa.String(length=255), nullable=True),
    sa.Column('helpline_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_index(op.f('username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'is_admin')
    op.drop_table('emergency_contacts')
    op.drop_table('contents')
    # ### end Alembic commands ###
