"""added new tables

Revision ID: 148196210887
Revises: a9d42be3c485
Create Date: 2025-09-12 09:10:42.775302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148196210887'
down_revision: Union[str, Sequence[str], None] = 'a9d42be3c485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'contents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_column('contents', 'user_id')
    # ### end Alembic commands ###
