"""added new tables

Revision ID: 336dfd12e8d4
Revises: 5db3b9e8405c
Create Date: 2025-09-12 11:29:32.730813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '336dfd12e8d4'
down_revision: Union[str, Sequence[str], None] = '5db3b9e8405c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('type', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
