"""removed id and title

Revision ID: fa4862f4dab6
Revises: 336dfd12e8d4
Create Date: 2025-09-15 12:13:26.418763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa4862f4dab6'
down_revision: Union[str, Sequence[str], None] = '336dfd12e8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
